import PackingListScreen from "../../components/PackingListScreen";

const backpackCategories = [
  {
    title: "Apteczka",
    items: [
      "Plastry",
      "Plaster bezopatrunkowy – taśma",
      "Plaster bezopatrunkowy – arkusz",
      "Hydrożel",
      "Bandaż 10 cm",
      "Bandaż półelastyczny 5 cm",
      "Gazy jałowe",
      "Podpaski",
      "Koc NRC",
      "Chusta trójkątna",
      "Rękawiczki",
      "Termometr",
      "Nożyczki",
      "Pilniczek",
      "Sól fizjologiczna",
      "Gaziki alkoholowe",
      "Chusteczki dekontaminacyjne",
      "Octenisept",
      "Wapno",
      "Theraflu",
      "Elektrolity",
      "Leki na gardło",
      "Leki przeciwbólowe",
      "Leki rozkurczowe",
    ],
  },
  {
    title: "Portfel",
    items: [
      "Gotówka",
      "Karty płatnicze",
      "Legitymacja",
      "Dowód osobisty",
      "PEKA",
      "EKUZ",
      "Karta biblioteczna",
      "Karty lojalnościowe",
      "Naklejki",
      "Pendrive",
      "Multitool",
      "Gumki",
      "Drut",
    ],
  },
  {
    title: "Kubek",
    items: [
      "Siatki",
      "Grzałka",
      "Baton",
      "Rolka do ubrań",
      "Taśma klejąca",
      "Gąbka i płyn do naczyń",
      "Sznurek i klamerki",
      "Trytytki",
    ],
  },
  {
    title: "Zewnętrzne",
    items: ["Długopis", "Marker", "Parasol", "Bidon/termos"],
  },
  {
    title: "Laptop",
    items: [
      "Laptop",
      "Teczka",
      "Wkładka",
      "Dokumenty",
      "Kartki, koperty, bilety",
    ],
  },
  {
    title: "Mała kieszeń",
    items: [
      "Chusteczki higieniczne",
      "Chusteczki mokre",
      "Chusteczki do ekranów",
      "Nakładki na toaletę",
      "Krem",
      "Mydło",
      "Perfum",
      "Płyn do dezynfekcji",
      "Grzebień",
      "Zapalniczka",
      "Przewody",
      "Adapter",
      "Słuchawki",
      "Zatyczki do uszu",
      "Klej na gorąco",
      "Baterie",
      "Pomadka",
      "Miara",
      "Zestaw biurowy",
      "Zestaw do szycia",
      "Otwieracz",
    ],
  },
  {
    title: "Jedzenie",
    items: [
      "Cukier",
      "Pieprz, sól",
      "Kawa, herbata",
      "Kisiel",
      "Guma do żucia",
    ],
  },
  {
    title: "Inne",
    items: [
      "Notes",
      "Sztućce",
      "Powerbank",
      "Rzeczy",
      "Dezodorant",
      "Okulary",
      "Ogrzewacz do rąk",
      "Głośnik",
      "Multitool",
      "Rękawice",
      "Torba na zakupy",
    ],
  },
];

export default function BackpackScreen() {
  return <PackingListScreen title="Plecak" categories={backpackCategories} />;
}
